<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocentesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('docentes')->insert([
            [
                'nombres' => 'Juan Carlos',
                'apellidos' => 'Prudencio Prado',
                'dni' => '56718345',
                'facultad_id' => 1,
                'departamento' => 'Sistemas',
                'celular' => '934567852',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'María Elena',
                'apellidos' => 'Gómez Torres',
                'dni' => '56718346',
                'facultad_id' => 1,
                'departamento' => 'Sistemas',
                'celular' => '934567853',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Luis Alberto',
                'apellidos' => 'Salazar Díaz',
                'dni' => '56718347',
                'facultad_id' => 2,
                'departamento' => 'Industrial',
                'celular' => '934567854',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Ana Lucía',
                'apellidos' => 'Ramírez Soto',
                'dni' => '56718348',
                'facultad_id' => 2,
                'departamento' => 'Industrial',
                'celular' => '934567855',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Carlos Eduardo',
                'apellidos' => 'Pérez Vargas',
                'dni' => '56718349',
                'facultad_id' => 3,
                'departamento' => 'Civil',
                'celular' => '934567856',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Gabriela Sofía',
                'apellidos' => 'López Herrera',
                'dni' => '56718350',
                'facultad_id' => 3,
                'departamento' => 'Civil',
                'celular' => '934567857',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Pedro Pablo',
                'apellidos' => 'Mendoza León',
                'dni' => '56718351',
                'facultad_id' => 1,
                'departamento' => 'Sistemas',
                'celular' => '934567858',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Sandra Milagros',
                'apellidos' => 'Cruz Paredes',
                'dni' => '56718352',
                'facultad_id' => 2,
                'departamento' => 'Industrial',
                'celular' => '934567859',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Ricardo Andrés',
                'apellidos' => 'Torres Guzmán',
                'dni' => '56718353',
                'facultad_id' => 3,
                'departamento' => 'Civil',
                'celular' => '934567860',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Patricia Elena',
                'apellidos' => 'Morales Silva',
                'dni' => '56718354',
                'facultad_id' => 1,
                'departamento' => 'Sistemas',
                'celular' => '934567861',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Fernando Javier',
                'apellidos' => 'Reyes Campos',
                'dni' => '56718355',
                'facultad_id' => 2,
                'departamento' => 'Industrial',
                'celular' => '934567862',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Carmen Rosa',
                'apellidos' => 'Aguilar Peña',
                'dni' => '56718356',
                'facultad_id' => 3,
                'departamento' => 'Civil',
                'celular' => '934567863',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Javier Enrique',
                'apellidos' => 'Sánchez Flores',
                'dni' => '56718357',
                'facultad_id' => 1,
                'departamento' => 'Sistemas',
                'celular' => '934567864',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Paola Andrea',
                'apellidos' => 'Vargas Medina',
                'dni' => '56718358',
                'facultad_id' => 2,
                'departamento' => 'Industrial',
                'celular' => '934567865',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Miguel Ángel',
                'apellidos' => 'Castro Ponce',
                'dni' => '56718359',
                'facultad_id' => 3,
                'departamento' => 'Civil',
                'celular' => '934567866',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Verónica Isabel',
                'apellidos' => 'Ortega Ruiz',
                'dni' => '56718360',
                'facultad_id' => 1,
                'departamento' => 'Sistemas',
                'celular' => '934567867',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Oscar Daniel',
                'apellidos' => 'Rojas Cabrera',
                'dni' => '56718361',
                'facultad_id' => 2,
                'departamento' => 'Industrial',
                'celular' => '934567868',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Silvia Teresa',
                'apellidos' => 'Navarro Salas',
                'dni' => '56718362',
                'facultad_id' => 3,
                'departamento' => 'Civil',
                'celular' => '934567869',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Lucía Fernanda',
                'apellidos' => 'Ramírez Soto',
                'dni' => '56718363',
                'facultad_id' => 1,
                'departamento' => 'Sistemas',
                'celular' => '934567870',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Marco Antonio',
                'apellidos' => 'Huaney Gonzales',
                'dni' => '56718364',
                'facultad_id' => 2,
                'departamento' => 'Industrial',
                'celular' => '934567871',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
