<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EstudiantesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('estudiantes')->insert([
            [
                'nombres' => 'Marco Antonio',
                'apellidos' => 'Huaney Gonzales',
                'codigo_universidad' => '171.2436.010',
                'dni' => '67563445',
                'celular' => '934525473',
                'facultad_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Lucía Fernanda',
                'apellidos' => 'Ramírez Soto',
                'codigo_universidad' => '171.2436.011',
                'dni' => '67563446',
                'celular' => '934525474',
                'facultad_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Carlos Eduardo',
                'apellidos' => 'Pérez Vargas',
                'codigo_universidad' => '171.2436.012',
                'dni' => '67563447',
                'celular' => '934525475',
                'facultad_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Ana María',
                'apellidos' => 'García Torres',
                'codigo_universidad' => '171.2436.013',
                'dni' => '67563448',
                'celular' => '934525476',
                'facultad_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Jorge Luis',
                'apellidos' => 'Salazar Díaz',
                'codigo_universidad' => '171.2436.014',
                'dni' => '67563449',
                'celular' => '934525477',
                'facultad_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'María José',
                'apellidos' => 'Vega Ríos',
                'codigo_universidad' => '171.2436.015',
                'dni' => '67563450',
                'celular' => '934525478',
                'facultad_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Pedro Pablo',
                'apellidos' => 'Mendoza León',
                'codigo_universidad' => '171.2436.016',
                'dni' => '67563451',
                'celular' => '934525479',
                'facultad_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Sandra Milagros',
                'apellidos' => 'Cruz Paredes',
                'codigo_universidad' => '171.2436.017',
                'dni' => '67563452',
                'celular' => '934525480',
                'facultad_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Luis Alberto',
                'apellidos' => 'Quispe Ramos',
                'codigo_universidad' => '171.2436.018',
                'dni' => '67563453',
                'celular' => '934525481',
                'facultad_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Patricia Elena',
                'apellidos' => 'Morales Silva',
                'codigo_universidad' => '171.2436.019',
                'dni' => '67563454',
                'celular' => '934525482',
                'facultad_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Ricardo Andrés',
                'apellidos' => 'Torres Guzmán',
                'codigo_universidad' => '171.2436.020',
                'dni' => '67563455',
                'celular' => '934525483',
                'facultad_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Gabriela Sofía',
                'apellidos' => 'López Herrera',
                'codigo_universidad' => '171.2436.021',
                'dni' => '67563456',
                'celular' => '934525484',
                'facultad_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Fernando Javier',
                'apellidos' => 'Reyes Campos',
                'codigo_universidad' => '171.2436.022',
                'dni' => '67563457',
                'celular' => '934525485',
                'facultad_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Carmen Rosa',
                'apellidos' => 'Aguilar Peña',
                'codigo_universidad' => '171.2436.023',
                'dni' => '67563458',
                'celular' => '934525486',
                'facultad_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Javier Enrique',
                'apellidos' => 'Sánchez Flores',
                'codigo_universidad' => '171.2436.024',
                'dni' => '67563459',
                'celular' => '934525487',
                'facultad_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Paola Andrea',
                'apellidos' => 'Vargas Medina',
                'codigo_universidad' => '171.2436.025',
                'dni' => '67563460',
                'celular' => '934525488',
                'facultad_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Miguel Ángel',
                'apellidos' => 'Castro Ponce',
                'codigo_universidad' => '171.2436.026',
                'dni' => '67563461',
                'celular' => '934525489',
                'facultad_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Verónica Isabel',
                'apellidos' => 'Ortega Ruiz',
                'codigo_universidad' => '171.2436.027',
                'dni' => '67563462',
                'celular' => '934525490',
                'facultad_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Oscar Daniel',
                'apellidos' => 'Rojas Cabrera',
                'codigo_universidad' => '171.2436.028',
                'dni' => '67563463',
                'celular' => '934525491',
                'facultad_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Silvia Teresa',
                'apellidos' => 'Navarro Salas',
                'codigo_universidad' => '171.2436.029',
                'dni' => '67563464',
                'celular' => '934525492',
                'facultad_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
